name: Build

on:
  # Trigger the workflow on pushes to the master or (any) pull request
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  PY_COLORS: "1"

jobs:
  build:
    name: ${{ matrix.os }} (py ${{ matrix.version }}${{ matrix.special }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        version: ['3.8', '3.9', '3.10', '3.11']
        special: ['']
        include:
          - os: ubuntu-latest
            special: '; pre-release'
            version: '3.11'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          case "${{ matrix.special }}" in
            "pre-release")
              pip install --pre -e .[docs,test] --upgrade --force-reinstall ;;
            *)
              pip install -e .[docs,test] ;;
          esac

      - name: show python version
        run: python --version

      - name: show installed packages
        run: pip list

      - name: Test
        run: pytest

      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          name: codecov-umbrella
